name: Python CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.py"
      - ".github/workflows/*.yml"
  push:
    branches:
      - main
    paths:
      - "**.py"
      - ".github/workflows/*.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.lock

      - name: Lint with pylint
        run: |
          pylint --version
          pylint ./**/*.py

      - name: Type check with mypy
        run: |
          mypy --version
          mypy --check .

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.lock

      - name: Format check with black
        run: |
          black --version
          black --check .
          isort --check .

      - name: Format check with isort
        run: |
          isort --version
          isort --check .

  test:
    runs-on: ubuntu-latest
    needs: [lint, format]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.lock

      - name: Test with pytest
        run: pytest
