name: Python CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.py"
      - ".github/workflows/*.yml"
  push:
    branches:
      - main
    paths:
      - "**.py"
      - ".github/workflows/*.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.lock ]; then pip install -r requirements.lock; fi

      - name: Lint with pylint
        run: |
          pip install pylint
          pylint ./**/*.py

      - name: Type check with mypy
        run: |
          pip install mypy
          mypy --check .

      - name: Format with black
        run: |
          pip install black
          black --check .

      - name: Test with pytest
        run: |
          pip install pytest
          pytest
